// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5d30121f-5330-4549-abc5-e53eb31ea3a0";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onEmergencyChange();


float bodyTempC1;
float roomTemp1;
int beatAvg1;
int humidity1;
CloudSwitch emergency;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(bodyTempC1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(roomTemp1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(beatAvg1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(emergency, READWRITE, ON_CHANGE, onEmergencyChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
