// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8c07edb7-dd18-44a2-8291-3ef0420f98f6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float airPressure1;
int fanSpeed1;
CloudLocation location1;
bool fireAlert;
bool smokeAlert;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(airPressure1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(fanSpeed1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(location1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(fireAlert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(smokeAlert, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
